clone = "github.com"
user = "fioncat"
email = "lazycat7706@gmail.com"
ssh = false
provider = "github"
token = "${GITHUB_TOKEN}"

icon = "ï‚›"

[owners.fioncat]
labels = ["pin", "sync"]
ssh = true

[owners.ucloud]
labels = ["pin", "sync"]
ssh = true

[owners.catus-project]
labels = ["pin", "sync"]
ssh = true

[owners.kubernetes]
alias = "k8s"
repo_alias.kubernetes = "k8s"
